spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/poc_management
    password: Softtek@2022
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  application:
    name: Customer-Service
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  port: '9902'
